meta_product_name: "Trashtag"
meta_title: "Trashtag - It's time to save the earth, more than ever"
meta_description: "Too many plastics, too many sea animals suffering, we need you!"
meta_image: "background1200.jpg" # should exist in `app/assets/images/`
